language: node_js

node_js:
- '8'

env:
  - REMOTE_LOCATION=$SERVER_USERNAME@$SERVER_HOSTNAME:/home/$SERVER_USERNAME/public_html

install:
- npm install

script:
- hexo generate

before_deploy:
- echo -e "Host deploy\n\tHostname $SERVER_HOSTNAME\n\tPort $SERVER_PORT\n\tUser $SERVER_USERNAME\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_166da6ee0d78_key -iv $encrypted_166da6ee0d78_iv -in deploy_key.enc -out /tmp/deploy_key -d
- chmod 600 /tmp/deploy_key
- eval "$(ssh-agent -s)"
- ssh-add /tmp/deploy_key

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -az --stats --delete --exclude='files/' -e "ssh -p $SERVER_PORT" ./public/ $REMOTE_LOCATION
  on:
    branch: master
