dist: xenial

addons:
  # Adds prod server key to known hosts
  ssh_known_hosts: $SERVER_HOSTNAME:$SERVER_PORT

git:
  # Handle git submodules yourself
  submodules: false

before_install:
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  # install Hugo 0.52 extended version
  - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_extended_0.52_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  # builds Hugo website
  - hugo

before_deploy:
  # decrypts private deploy key and adds to ssh agent
  - openssl aes-256-cbc -K $encrypted_bcf774b7103b_key -iv $encrypted_bcf774b7103b_iv -in travis_rsa.enc -out /tmp/travis_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/travis_rsa
  - ssh-add /tmp/travis_rsa

deploy:
  # deploys website via ssh rsync to prod server
  provider: script
  skip_cleanup: true
  script: rsync -az --stats --delete --exclude='files/' -e "ssh -p $SERVER_PORT" ./public/ $SERVER_USERNAME@$SERVER_HOSTNAME:/home/$SERVER_USERNAME/public_html
  on:
    branch: master