baseURL = "https://torresbaldi.com/"
languageCode = "en-us"
title = "Torres Baldi Studio"
description = "Indie Game Makers"
theme = "bulmin"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  mainSections = ["blog"]
