baseURL = "https://torresbaldi.com/"
title = "Torres Baldi Studio"
theme = "bulmin"
disableKinds = ["taxonomy", "taxonomyTerm"]
DefaultContentLanguage = "es"

[languages]
  [languages.es]
  	languageName = "Español"
  	languageCode = "es-AR"

[params]
  description = "Indie Game Makers"
  mainSections = ["blog"]
